"DataclassNestedTypes": {
  shape: class
  +node_map: "dict[str, Optional[DataclassRelatedNode]]"
  +node_groups: "list[list[DataclassRelatedNode]]"
}

"DataclassRelatedNode": {
  shape: class
  +name: str
}

"DataclassNestedTypes" -> "DataclassRelatedNode": "node_groups" {
  target-arrowhead.shape: cf-many
}

"DataclassNestedTypes" -> "DataclassRelatedNode": "node_map" {
  target-arrowhead.shape: cf-many
}
