"DataclassAltNode": {
  shape: class
  +name: str
}

"DataclassRelatedNode": {
  shape: class
  +name: str
}

"DataclassUnionSemantics": {
  shape: class
  +union_node: "Union[DataclassRelatedNode, DataclassAltNode]"
  +optional_union_node: "Optional[Union[DataclassRelatedNode, DataclassAltNode]]"
}

"DataclassUnionSemantics" -> "DataclassAltNode": "optional_union_node" {
  target-arrowhead.shape: cf-one
}

"DataclassUnionSemantics" -> "DataclassRelatedNode": "optional_union_node" {
  target-arrowhead.shape: cf-one
}

"DataclassUnionSemantics" -> "DataclassAltNode": "union_node" {
  target-arrowhead.shape: cf-one-required
}

"DataclassUnionSemantics" -> "DataclassRelatedNode": "union_node" {
  target-arrowhead.shape: cf-one-required
}
