"MsgspecNestedTypes": {
  shape: class
  +node_map: "dict[str, Optional[MsgspecRelatedNode]]"
  +node_groups: "list[list[MsgspecRelatedNode]]"
}

"MsgspecRelatedNode": {
  shape: class
  +name: str
}

"MsgspecNestedTypes" -> "MsgspecRelatedNode": "node_groups" {
  target-arrowhead.shape: cf-many
}

"MsgspecNestedTypes" -> "MsgspecRelatedNode": "node_map" {
  target-arrowhead.shape: cf-many
}
