"MsgspecRecursive": {
  shape: class
  +parent: "Optional[MsgspecRecursive]"
  +children: "list[MsgspecRecursive]"
}

"MsgspecRecursive" -> "MsgspecRecursive": "children" {
  target-arrowhead.shape: cf-many
}

"MsgspecRecursive" -> "MsgspecRecursive": "parent" {
  target-arrowhead.shape: cf-one
}
